-- Tipo   : TABLE
-- Objeto : TB_LOG_CFE_REFORMA
-- Schema : USER_XMLS
-- Salvo  : 2026-06-03
-- Origem : Export do banco (Row Count: 0)
-- Nota   : Log de erros de processamento de CF-e (Cupom Fiscal Eletrônico) na Reforma Fiscal
--          Registra NOME_ARQUIVO, CHAVE_ACESSO, FORMATO_XML, ORA_CODE, ORA_MSG e BACKTRACE
-- ------------------------------------------------------------

DROP TABLE TB_LOG_CFE_REFORMA CASCADE CONSTRAINTS
/

CREATE TABLE TB_LOG_CFE_REFORMA
(
  ID_LOG            NUMBER GENERATED ALWAYS AS IDENTITY
                      ( START WITH 1 MAXVALUE 9999999999999999999999999999
                        MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE ) NOT NULL,
  DT_PROCESSAMENTO  TIMESTAMP(6)         DEFAULT SYSTIMESTAMP  NOT NULL,
  NOME_ARQUIVO      VARCHAR2(200 BYTE),
  CHAVE_ACESSO      VARCHAR2(44 BYTE),
  NITEM             NUMBER,
  FORMATO_XML       VARCHAR2(10 BYTE),
  ORIGEM            VARCHAR2(200 BYTE),
  ORA_CODE          NUMBER,
  ORA_MSG           VARCHAR2(4000 BYTE),
  BACKTRACE         VARCHAR2(4000 BYTE)
)
TABLESPACE TBS_APEX
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
NOCOMPRESS
INMEMORY MEMCOMPRESS FOR QUERY LOW PRIORITY NONE DISTRIBUTE AUTO FOR SERVICE DEFAULT NO DUPLICATE
NOCACHE
/

ALTER TABLE TB_LOG_CFE_REFORMA ADD (
  PRIMARY KEY (ID_LOG)
  USING INDEX
    TABLESPACE TBS_APEX PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
  ENABLE VALIDATE)
/
