-- Tipo   : TABLE + INDEXES
-- Objeto : TB_LOG_NFE_REFORMA
-- Schema : USER_XMLS
-- Salvo  : 2026-06-03
-- Origem : Export do banco (Row Count: 0)
-- Nota   : Log de erros da PRC_NFE_REFORMA_CONSOLIDADA — captura CHAVE_ACESSO, NITEM, SQLERRM e SQLCODE
-- ------------------------------------------------------------

DROP TABLE TB_LOG_NFE_REFORMA CASCADE CONSTRAINTS
/

CREATE TABLE TB_LOG_NFE_REFORMA
(
  ID_LOG          NUMBER GENERATED ALWAYS AS IDENTITY
                    ( START WITH 1479855 MAXVALUE 9999999999999999999999999999
                      MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE ) NOT NULL,
  NOME_PROCEDURE  VARCHAR2(100 BYTE)   DEFAULT 'PRC_NFE_REFORMA_CONSOLIDADA',
  CHAVE_ACESSO    VARCHAR2(44 BYTE),
  NITEM           NUMBER,
  CODIGO_ERRO     NUMBER,
  MENSAGEM_ERRO   VARCHAR2(4000 BYTE),
  DATA_ERRO       TIMESTAMP(6)         DEFAULT SYSTIMESTAMP,
  USUARIO_SESSAO  VARCHAR2(50 BYTE)    DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER')
)
TABLESPACE TBS_APEX
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
NOCOMPRESS
INMEMORY MEMCOMPRESS FOR QUERY LOW PRIORITY NONE DISTRIBUTE AUTO FOR SERVICE DEFAULT NO DUPLICATE
NOCACHE
/

-- PK
CREATE UNIQUE INDEX PK_LOG_NFE_REFORMA ON TB_LOG_NFE_REFORMA (ID_LOG)
NOLOGGING TABLESPACE TBS_APEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT)
/

ALTER TABLE TB_LOG_NFE_REFORMA ADD (
  CONSTRAINT PK_LOG_NFE_REFORMA PRIMARY KEY (ID_LOG)
  USING INDEX PK_LOG_NFE_REFORMA ENABLE VALIDATE)
/

-- Índices de consulta
CREATE INDEX IDX_LOG_REFORMA_CHAVE ON TB_LOG_NFE_REFORMA (CHAVE_ACESSO)
NOLOGGING TABLESPACE TBS_APEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT)
/

CREATE INDEX IDX_LOG_REFORMA_DATA ON TB_LOG_NFE_REFORMA (DATA_ERRO)
NOLOGGING TABLESPACE TBS_APEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT)
/
