-- Tipo   : TABLE
-- Objeto : TB_REFORMA_TRIBUTARIA_LOG
-- Schema : USER_XMLS
-- Salvo  : 2026-06-03
-- Origem : Export do banco (Row Count: 0)
-- Nota   : Log de erros da PRC_NFE_REFORMA_TRIBUTARIA — captura CHAVE_ACESSO, NITEM, ORA_CODE, ORA_MSG e BACKTRACE
-- ------------------------------------------------------------

DROP TABLE TB_REFORMA_TRIBUTARIA_LOG CASCADE CONSTRAINTS
/

CREATE TABLE TB_REFORMA_TRIBUTARIA_LOG
(
  ID_LOG            NUMBER GENERATED ALWAYS AS IDENTITY
                      ( START WITH 21 MAXVALUE 9999999999999999999999999999
                        MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE ) NOT NULL,
  DT_PROCESSAMENTO  TIMESTAMP(6)        DEFAULT SYSTIMESTAMP  NOT NULL,
  CHAVE_ACESSO      VARCHAR2(44 BYTE),
  NUMERO_NF         VARCHAR2(20 BYTE),
  NITEM             VARCHAR2(10 BYTE),
  ORIGEM            VARCHAR2(100 BYTE),
  ORA_CODE          NUMBER,
  ORA_MSG           VARCHAR2(4000 BYTE),
  BACKTRACE         VARCHAR2(4000 BYTE)
)
TABLESPACE TBS_APEX
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
NOCOMPRESS
INMEMORY MEMCOMPRESS FOR QUERY LOW PRIORITY NONE DISTRIBUTE AUTO FOR SERVICE DEFAULT NO DUPLICATE
NOCACHE
/

ALTER TABLE TB_REFORMA_TRIBUTARIA_LOG ADD (
  PRIMARY KEY (ID_LOG)
  USING INDEX
    TABLESPACE TBS_APEX PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT)
  ENABLE VALIDATE)
/
