-- Tipo   : TABLE
-- Objeto : TB_REFORMA_TRIBUTARIA
-- Schema : USER_XMLS
-- Salvo  : 2026-06-03
-- Origem : Export do banco (Row Count: 941)
-- Nota   : Tributos da Reforma Fiscal por item de NF-e: IS, IBS, CBS, monofásico, ZFM, ajustes, estornos
-- PK     : (CHAVE_ACESSO, NITEM, TIPO_DOCUMENTO)
-- ------------------------------------------------------------

DROP TABLE TB_REFORMA_TRIBUTARIA CASCADE CONSTRAINTS
/

CREATE TABLE TB_REFORMA_TRIBUTARIA
(
  TIPO_DOCUMENTO         VARCHAR2(5 BYTE),
  CHAVE_ACESSO           VARCHAR2(44 BYTE)  NOT NULL,
  NUMERO_NF              VARCHAR2(20 BYTE),
  DATA_EMISSAO           VARCHAR2(30 BYTE),
  NITEM                  NUMBER,
  -- IS — Imposto Seletivo
  IS_CST                 VARCHAR2(3 BYTE),
  IS_CCLASS_TRIB         VARCHAR2(6 BYTE),
  IS_VBC                 NUMBER,
  IS_PIS                 NUMBER,
  IS_PIS_ESPEC           NUMBER,
  IS_UTRIB               VARCHAR2(20 BYTE),
  IS_QTRIB               NUMBER,
  IS_VIS                 NUMBER,
  -- IBS / CBS
  IBSCBS_CST             VARCHAR2(3 BYTE),
  IBSCBS_CCLASS_TRIB     VARCHAR2(6 BYTE),
  IBS_VBC                NUMBER,
  IBS_VIBS               NUMBER,
  IBS_PIBSUF             NUMBER,
  IBS_VIBSUF             NUMBER,
  DEV_VTRIB              NUMBER,
  RED_PREDALIQ           NUMBER,
  RED_PALIQEFET          NUMBER,
  IBS_PIBSMUN            NUMBER,
  IBS_VIBSMUN            NUMBER,
  CBS_VBC                NUMBER,
  CBS_PCBS               NUMBER,
  CBS_VCBS               NUMBER,
  -- Regime Tributário diferenciado
  TRIB_REG_CST           VARCHAR2(3 BYTE),
  TRIB_REG_CCLASS_TRIB   VARCHAR2(6 BYTE),
  TRIB_REG_PALIQ_IBSUF   NUMBER,
  TRIB_REG_VTRIB_IBSUF   NUMBER,
  TRIB_REG_PALIQ_IBSMUN  NUMBER,
  TRIB_REG_VTRIB_IBSMUN  NUMBER,
  TRIB_REG_PALIQ_CBS     NUMBER,
  TRIB_REG_VTRIB_CBS     NUMBER,
  -- Compartilhamento Governamental
  COMP_GOV_PALIQ_IBSUF   NUMBER,
  COMP_GOV_VTRIB_IBSUF   NUMBER,
  COMP_GOV_PALIQ_IBSMUN  NUMBER,
  COMP_GOV_VTRIB_IBSMUN  NUMBER,
  COMP_GOV_PALIQ_CBS     NUMBER,
  COMP_GOV_VTRIB_CBS     NUMBER,
  -- Monofásico
  MONO_QBCMONO           NUMBER,
  MONO_ADREMIBS          NUMBER,
  MONO_ADREMCBS          NUMBER,
  MONO_VIBSMONO          NUMBER,
  MONO_VCBSMONO          NUMBER,
  MONO_RET_VBC           NUMBER,
  MONO_RET_QBCMONO       NUMBER,
  MONO_RET_ADREMIBS      NUMBER,
  MONO_RET_ADREMCBS      NUMBER,
  MONO_RET_VIBS          NUMBER,
  MONO_RET_VCBS          NUMBER,
  MONO_ANT_VBC           NUMBER,
  MONO_ANT_QBCMONO       NUMBER,
  MONO_ANT_ADREMIBS      NUMBER,
  MONO_ANT_ADREMCBS      NUMBER,
  MONO_ANT_VIBS          NUMBER,
  MONO_ANT_VCBS          NUMBER,
  MONO_DIF_PIBS          NUMBER,
  MONO_DIF_VIBS          NUMBER,
  MONO_DIF_PCBS          NUMBER,
  MONO_DIF_VCBS          NUMBER,
  -- Transferências, ZFM, Ajustes e Estornos
  TRANSF_VIBS            NUMBER,
  TRANSF_VCBS            NUMBER,
  ZFM_PIBS               NUMBER,
  ZFM_VIBS               NUMBER,
  ZFM_PCBS               NUMBER,
  ZFM_VCBS               NUMBER,
  AJ_COMP_VIBS           NUMBER,
  AJ_COMP_VCBS           NUMBER,
  ESTORNO_VIBS           NUMBER,
  ESTORNO_VCBS           NUMBER
)
TABLESPACE TBS_APEX
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
NOCOMPRESS
INMEMORY MEMCOMPRESS FOR QUERY LOW PRIORITY NONE DISTRIBUTE AUTO FOR SERVICE DEFAULT NO DUPLICATE
NOCACHE
/

CREATE UNIQUE INDEX PK_REF_TRIB ON TB_REFORMA_TRIBUTARIA (CHAVE_ACESSO, NITEM, TIPO_DOCUMENTO)
NOLOGGING TABLESPACE TBS_APEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT)
/

ALTER TABLE TB_REFORMA_TRIBUTARIA ADD (
  CONSTRAINT PK_REF_TRIB PRIMARY KEY (CHAVE_ACESSO, NITEM, TIPO_DOCUMENTO)
  USING INDEX PK_REF_TRIB ENABLE VALIDATE)
/
