-- Query para exportar ORBITAS_TABELAO2 com PREMIO (para análise de discriminação)
-- Período: histórico D-30 (17/04 a 15/05/2026) — excluir dia corrente (sem PREMIO conhecido)
-- Exportar como CSV com ; separador, salvar em: plsql/arquivo_csv/ORBITAS_TABELAO2_HISTORICO.csv

SELECT
    T1.PREMIO,
    T2.*
FROM DADOS_ORBITA DD
JOIN ORBITAS_TABELAO1 T1 ON T1.ID_DADOS_ORBITA = DD.ID_DADOS_ORBITA
JOIN ORBITAS_TABELAO2 T2 ON T2.ID_DADOS_ORBITA = DD.ID_DADOS_ORBITA
WHERE DD.TIMESTAMP_EXECUCAO_INS >= TO_DATE('17/04/2026', 'DD/MM/YYYY') + 18/24
  AND DD.TIMESTAMP_EXECUCAO_INS <  TO_DATE('16/05/2026', 'DD/MM/YYYY') + 19/24
ORDER BY DD.TIMESTAMP_EXECUCAO_INS, T1.ID_DADOS_ORBITA
