-- Tipo   : VIEW
-- Objeto : VW_METRICAS_MODELOS_IA_TOP9
-- Salvo  : 2026-05-14
-- Origem : Reestruturação — CTE para VW_TBL1_BKP, JOINs explícitos,
--          range de timestamp, aliases completos, duplicatas removidas
-- ------------------------------------------------------------
-- v1.1.0 - 2026-05-14 - Reestruturação completa via análise de código
-- v1.0.0 - original   - Versão gerada pelo QP5
-- ------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW VW_METRICAS_MODELOS_IA_TOP9
(
    ID_DADOS_ORBITA
  , DATA_EXECUCAO
  , CORRIDA
  , PREMIO
  , MILHAR
  , CONTEUDO_TXT
  , TIMESTAMP_EXECUCAO_INS
  , BICHO
)
BEQUEATH DEFINER
AS
   -- CTE: VW_TBL1_BKP consultada UMA ÚNICA VEZ em vez de ~90 subqueries escalares
   WITH BKP AS (
      SELECT * FROM VW_TBL1_BKP
   )
   SELECT DD.ID_DADOS_ORBITA
        , TRUNC(DD.TIMESTAMP_EXECUCAO_INS)   DATA_EXECUCAO
        , DD.CORRIDA
        , DD.PREMIO
        , DD.MILHAR
        , DD.TXT                             CONTEUDO_TXT
        , DD.TIMESTAMP_EXECUCAO_INS
        , DD.BICHO
     FROM DADOS_ORBITA              DD
     JOIN ORBITAS_TABELAO1          TAB1 ON TAB1.ID_DADOS_ORBITA = DD.ID_DADOS_ORBITA
     JOIN ORBITA_MILHARES_FILTRADAS F    ON F.ID_DADOS_ORBITA    = DD.ID_DADOS_ORBITA
     CROSS JOIN BKP
    WHERE DD.TIMESTAMP_EXECUCAO_INS          >= TRUNC(SYSDATE) + 18/24
      AND DD.TIMESTAMP_EXECUCAO_INS           < TRUNC(SYSDATE) + 19/24
      -- Filtros fixos
      AND TAB1.CONVERGENCIA__MONOTONICA        = 'N'
      AND TAB1.RAIZES__T_PRIMEIRA_RAIZ        IS NULL
      AND TAB1.RAIZES__TEM_RAIZ_NO_INTERVALO  = 'N'
      AND STR_PARA_NUMERO(TAB1.RAIZES__NUM_RAIZES_NO_INTERVAL) = 0
      AND TAB1.PLATO_ABISMO__ENCONTRADO        = 'S'
      AND STR_PARA_NUMERO(TAB1.TOTAL_BLOCOS)  BETWEEN 16 AND 17
      AND FNC_CONTAR_MILHARES(F.TXT)          = 1
      -- Filtros diretos
      AND TAB1.REGRESSAO_LINEAR__TENDENCIA    IN ('DESCENDO', 'SUBINDO')
      AND TAB1.AUTOCORRELACAO__TEM_MEMORIA    = 'N'
      AND TAB1.ZONAS_TRANSICAO__DIRECAO_DOM   IN ('DESCENDO', 'SUBINDO')
      AND TAB1.FORMA__DISTRIBUICAO            IN ('PLATICURTICA')
      AND STR_PARA_NUMERO(TAB1.ZONAS_TRANSICAO__TOTAL_TROCAS_)   >= 12
      AND STR_PARA_NUMERO(TAB1.ZONAS_TRANSICAO__ZONAS_DISTINT)   BETWEEN 7 AND 10
      AND STR_PARA_NUMERO(TAB1.DISTANCIA_PLATOS__NUM_PLATOS)      BETWEEN 0 AND 5
      AND NVL(STR_PARA_NUMERO(TAB1.DISTANCIA_PLATOS__DIST_MEDIA_P), 0) BETWEEN 0 AND 7
      AND (   TAB1.DISTANCIA_PLATOS__RITMO_SERIE IS NULL
           OR TAB1.DISTANCIA_PLATOS__RITMO_SERIE IN ('ESPACADO', 'REGULAR'))
      AND get_parte_decimal(TAB1.PERCENTIS__P25)  BETWEEN 0 AND 15
      AND get_parte_decimal(TAB1.PERCENTIS__IQR)  IN (0, 5, 75)
      AND TAB1.PERCENTIS__FINAL_NO_IQR            = 'S'
      -- Faixas via BKP (BASICO)
      AND STR_PARA_NUMERO(TAB1.BASICO__DESVIO)     BETWEEN BKP.BKP_MIN_BASICO__DESVIO     AND BKP.BKP_MAX_BASICO__DESVIO
      AND STR_PARA_NUMERO(TAB1.BASICO__MEDIA)      BETWEEN BKP.BKP_MIN_BASICO__MEDIA      AND BKP.BKP_MAX_BASICO__MEDIA
      AND STR_PARA_NUMERO(TAB1.BASICO__MIN)        BETWEEN BKP.BKP_MIN_BASICO__MIN        AND BKP.BKP_MAX_BASICO__MIN
      AND STR_PARA_NUMERO(TAB1.BASICO__MAX)        BETWEEN BKP.BKP_MIN_BASICO__MAX        AND BKP.BKP_MAX_BASICO__MAX
      AND STR_PARA_NUMERO(TAB1.BASICO__AMPLITUDE)  BETWEEN BKP.BKP_MIN_BASICO__AMPLITUDE  AND BKP.BKP_MAX_BASICO__AMPLITUDE
      -- Faixas via BKP (DERIVADAS)
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__D1_MEDIA)          BETWEEN BKP.BKP_MIN_DERIVADAS__D1_MEDIA          AND BKP.BKP_MAX_DERIVADAS__D1_MEDIA
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__D1_MAX)            BETWEEN BKP.BKP_MIN_DERIVADAS__D1_MAX            AND BKP.BKP_MAX_DERIVADAS__D1_MAX
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__D1_DESVIO)         BETWEEN BKP.BKP_MIN_DERIVADAS__D1_DESVIO         AND BKP.BKP_MAX_DERIVADAS__D1_DESVIO
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__D2_MEDIA)          BETWEEN BKP.BKP_MIN_DERIVADAS__D2_MEDIA          AND BKP.BKP_MAX_DERIVADAS__D2_MEDIA
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__D2_MAX)            BETWEEN BKP.BKP_MIN_DERIVADAS__D2_MAX            AND BKP.BKP_MAX_DERIVADAS__D2_MAX
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__D2_MIN)            BETWEEN BKP.BKP_MIN_DERIVADAS__D2_MIN            AND BKP.BKP_MAX_DERIVADAS__D2_MIN
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__FORCA_PARADA)      BETWEEN BKP.BKP_MIN_DERIVADAS__FORCA_PARADA      AND BKP.BKP_MAX_DERIVADAS__FORCA_PARADA
      AND STR_PARA_NUMERO(TAB1.DERIVADAS__MAGNITUDE_ABISMO)  BETWEEN BKP.BKP_MIN_DERIVADAS__MAGNITUDE_ABISMO  AND BKP.BKP_MAX_DERIVADAS__MAGNITUDE_ABISMO
      -- Faixas via BKP (POLINOMIAL)
      AND STR_PARA_NUMERO(TAB1.POLINOMIAL__COEF_A)             BETWEEN BKP.BKP_MIN_POLINOMIAL__COEF_A             AND BKP.BKP_MAX_POLINOMIAL__COEF_A
      AND STR_PARA_NUMERO(TAB1.POLINOMIAL__COEF_B)             BETWEEN BKP.BKP_MIN_POLINOMIAL__COEF_B             AND BKP.BKP_MAX_POLINOMIAL__COEF_B
      AND STR_PARA_NUMERO(TAB1.POLINOMIAL__COEF_C)             BETWEEN BKP.BKP_MIN_POLINOMIAL__COEF_C             AND BKP.BKP_MAX_POLINOMIAL__COEF_C
      AND STR_PARA_NUMERO(TAB1.POLINOMIAL__R2)                 BETWEEN BKP.BKP_MIN_POLINOMIAL__R2                 AND BKP.BKP_MAX_POLINOMIAL__R2
      AND STR_PARA_NUMERO(TAB1.POLINOMIAL__PONTO_INFLEXAO_T)   BETWEEN BKP.BKP_MIN_POLINOMIAL__PONTO_INFLEXAO_T   AND BKP.BKP_MAX_POLINOMIAL__PONTO_INFLEXAO_T
      AND STR_PARA_NUMERO(TAB1.POLINOMIAL__D2_NO_MEIO)         BETWEEN BKP.BKP_MIN_POLINOMIAL__D2_NO_MEIO         AND BKP.BKP_MAX_POLINOMIAL__D2_NO_MEIO
      -- Faixas via BKP (RAIZES)
      AND STR_PARA_NUMERO(TAB1.RAIZES__RAIZ_1)  BETWEEN BKP.BKP_MIN_RAIZES__RAIZ_1  AND BKP.BKP_MAX_RAIZES__RAIZ_1
      -- Faixas via BKP (PLATO_ABISMO)
      AND STR_PARA_NUMERO(TAB1.PLATO_ABISMO__TEMPO_RECARGA)  BETWEEN BKP.BKP_MIN_PLATO_ABISMO__TEMPO_RECARGA  AND BKP.BKP_MAX_PLATO_ABISMO__TEMPO_RECARGA
      -- Faixas via BKP (SUFIXO)
      AND STR_PARA_NUMERO(TAB1.SUFIXO__MEDIA)               BETWEEN BKP.BKP_MIN_SUFIXO__MEDIA               AND BKP.BKP_MAX_SUFIXO__MEDIA
      AND STR_PARA_NUMERO(TAB1.SUFIXO__MAX)                 BETWEEN BKP.BKP_MIN_SUFIXO__MAX                 AND BKP.BKP_MAX_SUFIXO__MAX
      AND STR_PARA_NUMERO(TAB1.SUFIXO__MIN)                 BETWEEN BKP.BKP_MIN_SUFIXO__MIN                 AND BKP.BKP_MAX_SUFIXO__MIN
      AND STR_PARA_NUMERO(TAB1.SUFIXO__DESVIO)              BETWEEN BKP.BKP_MIN_SUFIXO__DESVIO              AND BKP.BKP_MAX_SUFIXO__DESVIO
      AND STR_PARA_NUMERO(TAB1.SUFIXO__TENDENCIA_CRESCENTE) BETWEEN BKP.BKP_MIN_SUFIXO__TENDENCIA_CRESCENTE AND BKP.BKP_MAX_SUFIXO__TENDENCIA_CRESCENTE
      -- Faixas via BKP (ROTACAO / CONVERGENCIA)
      AND STR_PARA_NUMERO(TAB1.ROTACAO__DIGITOS_COMPARTILHADO)    BETWEEN BKP.BKP_MIN_ROTACAO__DIGITOS_COMPARTILHADO    AND BKP.BKP_MAX_ROTACAO__DIGITOS_COMPARTILHADO
      AND STR_PARA_NUMERO(TAB1.CONVERGENCIA__VELOCIDADE_CONVE)    BETWEEN BKP.BKP_MIN_CONVERGENCIA__VELOCIDADE_CONVE    AND BKP.BKP_MAX_CONVERGENCIA__VELOCIDADE_CONVE
      AND STR_PARA_NUMERO(TAB1.CONVERGENCIA__PERC_APROXIMACAO)    BETWEEN BKP.BKP_MIN_CONVERGENCIA__PERC_APROXIMACAO    AND BKP.BKP_MAX_CONVERGENCIA__PERC_APROXIMACAO
      -- Faixas via BKP (MOMENTUM)
      AND STR_PARA_NUMERO(TAB1.MOMENTUM__MOMENTUM)          BETWEEN BKP.BKP_MIN_MOMENTUM__MOMENTUM          AND BKP.BKP_MAX_MOMENTUM__MOMENTUM
      AND STR_PARA_NUMERO(TAB1.MOMENTUM__RAZAO_FINAL_TOTAL) BETWEEN BKP.BKP_MIN_MOMENTUM__RAZAO_FINAL_TOTAL AND BKP.BKP_MAX_MOMENTUM__RAZAO_FINAL_TOTAL
      -- Faixas via BKP (MEDIA_MOVEL)
      AND STR_PARA_NUMERO(TAB1.MEDIA_MOVEL__MM3_FINAL)   BETWEEN BKP.BKP_MIN_MEDIA_MOVEL__MM3_FINAL   AND BKP.BKP_MAX_MEDIA_MOVEL__MM3_FINAL
      AND STR_PARA_NUMERO(TAB1.MEDIA_MOVEL__MM5_FINAL)   BETWEEN BKP.BKP_MIN_MEDIA_MOVEL__MM5_FINAL   AND BKP.BKP_MAX_MEDIA_MOVEL__MM5_FINAL
      AND STR_PARA_NUMERO(TAB1.MEDIA_MOVEL__DESVIO_MM3)  BETWEEN BKP.BKP_MIN_MEDIA_MOVEL__DESVIO_MM3  AND BKP.BKP_MAX_MEDIA_MOVEL__DESVIO_MM3
      AND STR_PARA_NUMERO(TAB1.MEDIA_MOVEL__DESVIO_MM5)  BETWEEN BKP.BKP_MIN_MEDIA_MOVEL__DESVIO_MM5  AND BKP.BKP_MAX_MEDIA_MOVEL__DESVIO_MM5
      -- Faixas via BKP (PERCENTIS)
      AND STR_PARA_NUMERO(TAB1.PERCENTIS__P25)  BETWEEN BKP.BKP_MIN_PERCENTIS__P25  AND BKP.BKP_MAX_PERCENTIS__P25
      AND STR_PARA_NUMERO(TAB1.PERCENTIS__P50)  BETWEEN BKP.BKP_MIN_PERCENTIS__P50  AND BKP.BKP_MAX_PERCENTIS__P50
      AND STR_PARA_NUMERO(TAB1.PERCENTIS__P75)  BETWEEN BKP.BKP_MIN_PERCENTIS__P75  AND BKP.BKP_MAX_PERCENTIS__P75
      AND STR_PARA_NUMERO(TAB1.PERCENTIS__IQR)  BETWEEN BKP.BKP_MIN_PERCENTIS__IQR  AND BKP.BKP_MAX_PERCENTIS__IQR
      -- Faixas via BKP (FORMA)
      AND STR_PARA_NUMERO(TAB1.FORMA__SKEWNESS)  BETWEEN BKP.BKP_MIN_FORMA__SKEWNESS  AND BKP.BKP_MAX_FORMA__SKEWNESS
      AND STR_PARA_NUMERO(TAB1.FORMA__KURTOSIS)  BETWEEN BKP.BKP_MIN_FORMA__KURTOSIS  AND BKP.BKP_MAX_FORMA__KURTOSIS
      -- Faixas via BKP (REGRESSAO)
      AND STR_PARA_NUMERO(TAB1.REGRESSAO_LINEAR__SLOPE)  BETWEEN BKP.BKP_MIN_REGRESSAO_LINEAR__SLOPE  AND BKP.BKP_MAX_REGRESSAO_LINEAR__SLOPE
      -- Faixas via BKP (AUTOCORRELACAO)
      AND STR_PARA_NUMERO(TAB1.AUTOCORRELACAO__AC_LAG1)  BETWEEN BKP.BKP_MIN_AUTOCORRELACAO__AC_LAG1  AND BKP.BKP_MAX_AUTOCORRELACAO__AC_LAG1
      AND STR_PARA_NUMERO(TAB1.AUTOCORRELACAO__AC_LAG2)  BETWEEN BKP.BKP_MIN_AUTOCORRELACAO__AC_LAG2  AND BKP.BKP_MAX_AUTOCORRELACAO__AC_LAG2
      AND STR_PARA_NUMERO(TAB1.AUTOCORRELACAO__AC_LAG3)  BETWEEN BKP.BKP_MIN_AUTOCORRELACAO__AC_LAG3  AND BKP.BKP_MAX_AUTOCORRELACAO__AC_LAG3
;
